const SUCCESS_COMPLETE = "Successfully Updated Completed Case Stat"
const SUCCESS_RETREIVE = "Successfully Updated Retreive Case Stat"
const SOMETHING_WENT_WRONG = "Something Went Wrong"
const SUCCESS_MARKETERS = "Successfully Fetched Marketers"
const NOT_LESSER = "To-Date is not be lesser than From-Date"
const SUCCESS_PENDING = "Successfully Inserted Pending Stat"
const SUCCESS_DELETE = "Successfully Deleted Stat"
const FILE_UPLOAD = 'File uploaded and processed successfully'
const NO_FILE = 'No file uploaded'
const INVALID_FILE = 'Invalid file format. Please upload a CSV file.'
const SUCCESS_USERS = "Successfully Fetched Users"
const MARKETERS_NOT_THERE = "Marketers Data Not Found"
const PROCESS_SUCCESS = "Processed Successfully"
const REVENUE_MODIFIED_DATA = "Revenue modified data fetched successfully"
const REVENUE_STATS = "Revenue-stats fetched successfully"
const REVENUE_STAT_SINGLE = "Revenue record fetched successfully"
const DELETE_REVENUE_RAW = "Revenue Raw Data Deleted Successfully"
const DELETE_REVENUE_STAT = "Revenue Stats Data Deleted Successfully"
const PENDING_DATA = "Pending Data is Not Found!"
const PENDING = "PENDING"
const COMPLETED = "COMPLETED"
const MONTHLY_STATS_SUCCESS = "Monthly Stats Fetched Successfully"
const CASE_STATS_SUCCESS = "Case Type Stats Fetched Successfully"

const SUCCESS_FETCHED_SALES_REP = "Sales Reps Data Fetched Successfully"
const SINGLE_REP_FACILITY_WISE = "Single Rep Facility Wise Data Fetched Successfully"

const SUCCESS_MARKETER = "Marketer Fetched Successfully"

const SUCCESS_FETCHED_ONE_SALES_REP = 'Sales Rep Data Fetched Successfully'
const SUCCESS_FECTED_SALE_REP_REVENUE_STATS = "Revenue Stats Data Fetched Successfully"
const SUCCESS_FECTED_SALE_REP_VOLUME_STATS = "Volume Stats Data Fetched Successfully"
const SUCCESS_FETCHED_SALES_REP_OVERALL_REVENUE = 'Sales Rep Case Type Wise Overall Revenue Fetched Successfully'
const SUCCESS_FETCHED_SALES_REP_OVERALL_VOLUME = 'Sales Rep Case Type Wise Overall Volume Fetched Successfully'


const SUCCESS_FETCHED_SALE_VOLUME_MONTH_WISE = "Monthly Volume Fetched Sucessfully"
const SUCCESS_FETCHED_SALE_TREND_VOLUME = "Trends Volume Data Fetched Successfully"
const SUCCESS_FETCHED_SALES_REP_FACILITY_WISE_STATS = "Sales Reps Facilitiy Wise Stats Fetched Successfully"
const SUCCESS_FETCHED_SALES_REP_INSURANCE_PAYORS_DATA = 'Insurance payers data Fetched Successfully'
const SUCCESS_FETCHED_SALES_REP_INSURANCE_PAYORS_MONTH_WISE_DATA = 'Sales Representative Insurance Payors Month-Wise Data Fetched Successfully'
const SUCCESS_FETCHED_OVERVIEW_REVENUE_STATS = "Overview Revenue Stats Data Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_VOLUME_STATS = "Overview Volume Stats Data Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_REVENUE = "Revenue Data Fetched Successfully"

const SUCCESS_FETCHED_FACILITIES_REVENUE_STATS = "Facility Stats Revenue Fetched Successfully"
const SUCCESS_FETCHED_FACILITIES_VOLUME_STATS = "Facility Stats Volume Fetched Successfully"
const SUCCESSS_FETCHED_FACILITIES_CASES_TYPES_VOLUME = "Facility Case Type Volumes Fetched Successfully"
const SUCCESSS_FETCHED_FACILITIES_CASES_TYPES_REVENUE = "Facility Case Type Revenue Fetched Successfully"

const SUCCESS_FETCHED_FACILITY_CASE_TYPES_OVERALL_REVENUE = 'Facility Case Type Wise Overall Revenue Fetched Successfully'
const SUCCESS_FETCHED_FACILITY_CASE_TYPES_OVERALL_VOLUME = 'Facility Case Type Wise Overall Volume Fetched Successfully'

const SUCCESS_FETCHED_SALES_REP_VOLUME_AND_REVENUE = 'Sales Rep Case Types Volume And Revenue Data Fetched Successfully'
const SUCCESS_FETCHED_OVERVIEW_VOLUME_AND_REVENUE = 'Overview Case Types Volume And Revenue Data Fetched Successfully'
const SUCCESS_FETCHED_CASE_TYPES_REVENUE = 'Case Types Revenue Month Wise Data Fetched Successfully'
const SUCCESS_FETCHED_SALES_REP_CASE_TYPE_MONTHLY_VOLUME = 'Sales Rep Case Type Volume Month Wise Data Fetched Successfully'
const SUCCESS_FETCHED_FACILITY_CASE_TYPE_VOLUME_AND_REVENUE = 'Facility Case Type Volume and Revenue Date Fetched Successfully'
const SUCCESS_FETCHED_TREND_REVENUE = 'Trend Revenue Data Fetched Successfully'
const SUCCESS_FETCHED_SALES_REP_TREND_REVENUE = 'Sales Rep Trend Revenue Data Fetched Successfully'
const SUCCESS_FETCHED_SALES_REP_TREND_VOLUME = 'Sales Rep Trend Volume Data Fetched Successfully'


const SUCCESS_FETCHED_FACILITIES = "Facilities Fetched Successfully"
const SUCCESS_FETCHED_FACILITY = "Facility Fetched Successfully"
const SUCCESS_VOLUME_TREND = "Volume Trend Fetched Successfully"
const SUCCESS_FETCHED_CASE_TYPES = "Case Types Stats Data Fetched Successfully"
const SUCCESS_FETCHED_CASE_TYEPS_MONTH_WISE_REVENUE_DATA = 'Case Types Month Wise Revenue Data Fetched Successfully'
const SUCCESS_FETCHED_CASE_TYEPS_MONTH_WISE_VOLUME_DATA = 'Case Types Month Wise Volume Data Fetched Successfully'

const SUCCESS_FETCHED_REVENUE_MONTH_WISE_TRENDS = 'Case Types Revenue Month Wise Data Fetched Successfully'
const SUCCESS_FETCHED_INSURANCE_STATS = "Insurance stats fetched successfully"

const SUCCESS_FETCHED_FACILITIES_TRENDS_REVENUE = "Facility Trends Revenue Fetched Successfully"
const SUCCESS_FETCHED_FACILITIES_TRENDS_VOLUME = 'Facility Trends Volume Fetched Successfully'
const SUCCESS_FETCHED_FACILITY_INSURANCE_REVENUE_DATA = "Facilitices Insurance Payors Month-Wise Revenue Data Fetched Successfully"

const SUCCESS_FETCHED_FACILITY_INSURANCE_PAYORS = 'Facility Insurance Payors data Fetched Successfully'
const SUCCESS_FETCHED_OVERVIEW_STATS_REVENUE = "Overview Revenue Stats Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_STATS_VOLUME = "Overview Volume Stats Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_CASE_TYPES_REVENUE = "Overview Case Types Revenue Data Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_CASE_TYPES_VOLUME = "Overview Case Types Volume Data Fetched Successfully"
const SUCCESS_FETCHED_OVERVIEW_REVNUE = "Overview Revenue Data Fetched Successfully"

const SUCCESS_FETCHED_ALL_INSURANCES_DATA = "Insurance Payors Data Fetched Successfully"
const SUCCESS_FETCHED_INSURANCE_CASE_TYPES_DATA = "Insurance Case Type Wise Data Fetched Successfully"
const SUCCESS_FTECHED_INSURANCE_TRENDS_REVENUE = "Insurance Revenue Trends Data Fetched Successfully"
const SUCCESS_FETECHED_INSURANCE_TRENDS_VOLUME = "Insurance Volume Trends Data Fetched Successfully"
const SUCCESS_FETCHED_INSURANCE_PAYORS_DETAILS = "Insurance Payor Details Fetched Successfully"


const SUCCESS_DELETED_DATA_IN_TABLE = 'Successfully Deleted Data In Table'
const SUCCESS_FETCHED_PATIENT_CLAIMS_COUNT = 'Patient Claims Count Fetched Successfully'

const SUCCESS_SYNCED_INSURANCE_PAYORS = 'Insurance Payors Synced To Analytics Successfully'
const SUCCESS_SYNCED_CASE_TYPES = 'Case Types Synced To Analytics Successfully'

const CASE_TYPES_NOT_FOUND_IN_LIS_DATABASE = 'Case Types Not Found In LIS Database'
const NO_NEW_CASE_TYPES_TO_SYNC_WITH_ANALYTICS = 'No New Case Types To Sync With Analytics Database'

const INSURANCE_PAYORS_NOT_FOUND_IN_LIS_DATABASE = 'Insurance Payors Not Found In LIS Database'
const NO_NEW_INSURANCE_PAYORS_TO_SYNC_WITH_ANALYTICS = 'No New Insurance Payors To Sync With Analytics Database'


export {
    SUCCESS_COMPLETE, SUCCESS_RETREIVE, SOMETHING_WENT_WRONG, SUCCESS_MARKETERS, NOT_LESSER,
    SUCCESS_PENDING, SUCCESS_DELETE, FILE_UPLOAD, NO_FILE, INVALID_FILE, SUCCESS_USERS, MARKETERS_NOT_THERE,
    REVENUE_MODIFIED_DATA, REVENUE_STATS, DELETE_REVENUE_RAW, DELETE_REVENUE_STAT, PROCESS_SUCCESS, REVENUE_STAT_SINGLE,
    PENDING_DATA, PENDING, COMPLETED, MONTHLY_STATS_SUCCESS, CASE_STATS_SUCCESS, SUCCESS_FETCHED_SALES_REP, SINGLE_REP_FACILITY_WISE, SUCCESS_MARKETER,
    SUCCESS_FECTED_SALE_REP_REVENUE_STATS, SUCCESS_FECTED_SALE_REP_VOLUME_STATS, SUCCESS_FETCHED_SALE_VOLUME_MONTH_WISE,
    SUCCESS_FETCHED_SALES_REP_VOLUME_AND_REVENUE, SUCCESS_FETCHED_CASE_TYPES_REVENUE, SUCCESS_FETCHED_FACILITY_CASE_TYPE_VOLUME_AND_REVENUE,
    SUCCESS_FETCHED_OVERVIEW_REVENUE_STATS, SUCCESS_FETCHED_OVERVIEW_VOLUME_STATS, SUCCESS_FETCHED_OVERVIEW_REVENUE,
    SUCCESS_FETCHED_FACILITIES, SUCCESS_FETCHED_FACILITY, SUCCESS_VOLUME_TREND, SUCCESS_FETCHED_CASE_TYPES,
    SUCCESS_FETCHED_TREND_REVENUE, SUCCESS_FETCHED_SALE_TREND_VOLUME, SUCCESS_FETCHED_FACILITIES_REVENUE_STATS, SUCCESS_FETCHED_FACILITIES_VOLUME_STATS,
    SUCCESSS_FETCHED_FACILITIES_CASES_TYPES_VOLUME, SUCCESS_FETCHED_REVENUE_MONTH_WISE_TRENDS, SUCCESS_FETCHED_OVERVIEW_VOLUME_AND_REVENUE,
    SUCCESS_FETCHED_INSURANCE_STATS, SUCCESS_FETCHED_FACILITIES_TRENDS_REVENUE, SUCCESS_FETCHED_FACILITIES_TRENDS_VOLUME,
    SUCCESSS_FETCHED_FACILITIES_CASES_TYPES_REVENUE, SUCCESS_FETCHED_FACILITY_INSURANCE_PAYORS, SUCCESS_FETCHED_SALES_REP_CASE_TYPE_MONTHLY_VOLUME,
    SUCCESS_FETCHED_SALES_REP_FACILITY_WISE_STATS, SUCCESS_FETCHED_SALES_REP_INSURANCE_PAYORS_DATA, SUCCESS_FETCHED_SALES_REP_TREND_REVENUE,
    SUCCESS_FETCHED_SALES_REP_TREND_VOLUME, SUCCESS_FETCHED_OVERVIEW_STATS_REVENUE, SUCCESS_FETCHED_OVERVIEW_STATS_VOLUME,
    SUCCESS_FETCHED_OVERVIEW_REVNUE, SUCCESS_FETCHED_ALL_INSURANCES_DATA, SUCCESS_FETCHED_INSURANCE_CASE_TYPES_DATA, SUCCESS_FTECHED_INSURANCE_TRENDS_REVENUE,
    SUCCESS_FETECHED_INSURANCE_TRENDS_VOLUME, SUCCESS_DELETED_DATA_IN_TABLE, SUCCESS_FETCHED_PATIENT_CLAIMS_COUNT, SUCCESS_FETCHED_ONE_SALES_REP, SUCCESS_FETCHED_INSURANCE_PAYORS_DETAILS,
    SUCCESS_FETCHED_SALES_REP_INSURANCE_PAYORS_MONTH_WISE_DATA, SUCCESS_FETCHED_SALES_REP_OVERALL_REVENUE, SUCCESS_FETCHED_SALES_REP_OVERALL_VOLUME,
    SUCCESS_FETCHED_FACILITY_CASE_TYPES_OVERALL_REVENUE, SUCCESS_FETCHED_FACILITY_CASE_TYPES_OVERALL_VOLUME,
    SUCCESS_FETCHED_OVERVIEW_CASE_TYPES_REVENUE, SUCCESS_FETCHED_OVERVIEW_CASE_TYPES_VOLUME, SUCCESS_FETCHED_CASE_TYEPS_MONTH_WISE_REVENUE_DATA, SUCCESS_FETCHED_FACILITY_INSURANCE_REVENUE_DATA,
    SUCCESS_FETCHED_CASE_TYEPS_MONTH_WISE_VOLUME_DATA, SUCCESS_SYNCED_INSURANCE_PAYORS, SUCCESS_SYNCED_CASE_TYPES, CASE_TYPES_NOT_FOUND_IN_LIS_DATABASE, INSURANCE_PAYORS_NOT_FOUND_IN_LIS_DATABASE,
    NO_NEW_CASE_TYPES_TO_SYNC_WITH_ANALYTICS, NO_NEW_INSURANCE_PAYORS_TO_SYNC_WITH_ANALYTICS
}
